//! The "errlanes stand-in" side of the two-crate coherence fixture: it declares
//! carriers that a separate downstream crate then converts, widens, narrows,
//! and absorbs. Every impl here is generated by
//! `#[derive(errlanes::Carrier)]`; nothing is hand-written.

#[derive(Debug, Clone, thiserror::Error, errlanes::Rejection)]
#[rejection(error = manual)]
pub enum DepositRejection {
    #[error("deposit account is frozen")]
    AccountFrozen,
    #[error("deposit exceeds the daily limit")]
    #[rejection(level = "warn")]
    DailyLimitExceeded,
}

/// A fault-only carrier: reads and host calls.
#[derive(Debug, errlanes::Carrier)]
pub enum HostFault {
    Transient(errlanes::Transient),
    Fatal(errlanes::Fatal),
}

/// Same lanes as [`HostFault`], deliberately a distinct type.
#[derive(Debug, errlanes::Carrier)]
pub enum RepoFault {
    Transient(errlanes::Transient),
    Fatal(errlanes::Fatal),
}

/// A single-lane carrier, to pin the bare-`Fatal` outbound `?`.
#[derive(Debug, errlanes::Carrier)]
pub enum OnlyFatal {
    Fatal(errlanes::Fatal),
}

/// A carrier that can reject, with a declared rejection.
#[derive(Debug, errlanes::Carrier)]
pub enum DepositError {
    Rejected(DepositRejection),
    Transient(errlanes::Transient),
    Fatal(errlanes::Fatal),
}

/// A carrier that is generic over its rejection.
#[derive(Debug, errlanes::Carrier)]
pub enum WriteError<R> {
    Rejected(R),
    Transient(errlanes::Transient),
    Fatal(errlanes::Fatal),
}

pub fn frozen() -> DepositError {
    DepositError::Rejected(DepositRejection::AccountFrozen)
}

pub fn transient() -> DepositError {
    DepositError::Transient(errlanes::Transient::new(errlanes::TransientKind::Deadlock))
}

pub fn host_op() -> Result<u8, HostFault> {
    Ok(7)
}

pub fn host_transient() -> Result<u8, HostFault> {
    Err(HostFault::Transient(errlanes::Transient::new(
        errlanes::TransientKind::Deadlock,
    )))
}

pub fn repo_op() -> Result<u8, RepoFault> {
    Ok(8)
}
