//! The "errlanes stand-in" side of the two-crate coherence fixture: it declares
//! carriers that a separate downstream crate then converts, widens, narrows,
//! and absorbs. Every impl here is generated by `#[errlanes::fault]` /
//! `#[errlanes::fail]`; nothing is hand-written.

#[derive(Debug, Clone, thiserror::Error, errlanes::Rejection)]
#[rejection(error = manual)]
pub enum DepositRejection {
    #[error("deposit account is frozen")]
    AccountFrozen,
    #[error("deposit exceeds the daily limit")]
    #[rejection(level = "warn")]
    DailyLimitExceeded,
}

/// A fault-only carrier: reads and host calls.
#[errlanes::fault(Transient, Fatal)]
pub struct HostFault;

/// Same lanes as [`HostFault`], deliberately a distinct type.
#[errlanes::fault(Transient, Fatal)]
pub struct RepoFault;

/// A single-lane carrier, to pin the bare-`Fatal` outbound `?`.
#[errlanes::fault(Fatal)]
pub struct OnlyFatal;

/// A carrier that can reject, with a declared rejection.
#[errlanes::fail(DepositRejection; Transient, Fatal)]
pub struct DepositError;

/// A carrier that is generic over its rejection.
#[errlanes::fail(R; Transient, Fatal)]
pub struct WriteError<R>;

pub fn frozen() -> DepositError {
    DepositError::Rejected(DepositRejection::AccountFrozen)
}

pub fn transient() -> DepositError {
    DepositError::Transient(errlanes::Transient::new(errlanes::TransientKind::Deadlock))
}

pub fn host_op() -> Result<u8, HostFault> {
    Ok(7)
}

pub fn host_transient() -> Result<u8, HostFault> {
    Err(HostFault::Transient(errlanes::Transient::new(
        errlanes::TransientKind::Deadlock,
    )))
}

pub fn repo_op() -> Result<u8, RepoFault> {
    Ok(8)
}
