[package]
name = "repo-composition-source"
version = "0.16.4-dev"
edition = "2024"
license = "Apache-2.0"
publish = false
[dependencies]
tracing = "0.1"
es-entity = { path = "../../.." }
errlanes = { path = "../../../errlanes", features = ["derive"] }
serde = { workspace = true }
derive_builder = { workspace = true }
sqlx = { workspace = true }
