//! Types for working with errors produced by es-entity.

use thiserror::Error;

/// Error type for entity hydration failures (reconstructing entities from events).
#[derive(Error, Debug)]
pub enum EntityHydrationError {
    #[error("EntityHydrationError - UninitializedFieldError: {0}")]
    UninitializedFieldError(#[from] derive_builder::UninitializedFieldError),
    #[error("EntityHydrationError - Deserialization: {0}")]
    EventDeserialization(#[from] serde_json::Error),
}

/// Trait for error types that can represent a "not found" condition.
///
/// Implemented by error types used with `EsQuery::fetch_one`, which needs
/// to produce a "not found" error when no rows match.
pub trait FromNotFound {
    fn not_found(entity: &'static str, column: &'static str, value: String) -> Self;
}

/// Trait for error types that can represent a concurrent modification conflict.
///
/// Implemented by `CreateError` and `ModifyError` types generated by `#[derive(EsRepo)]`.
pub trait FromConcurrentModification {
    fn concurrent_modification() -> Self;
}

#[derive(Error, Debug)]
#[error("CursorDestructureError: couldn't turn {0} into {1}")]
pub struct CursorDestructureError(&'static str, &'static str);

impl From<(&'static str, &'static str)> for CursorDestructureError {
    fn from((name, variant): (&'static str, &'static str)) -> Self {
        Self(name, variant)
    }
}
