//! Control and customize the query execution and its response.

/// Controls the sorting order when listing the entities from the database
///
/// `ListDirection` enum is used to specify order when listing entities from the database using [`EsRepo`][crate::EsRepo]
/// generated functions like `list_by`, `list_for` and `list_for_filters`. Has two variants: `Ascending` and `Descending`
///
/// # Examples
///
/// ```ignore
/// // List users by ID in ascending order (oldest first)
/// let paginated_users_asc = users.list_by_id(
///     PaginatedQueryArgs { first: 5, after: None },
///     ListDirection::Ascending, // or just Default::default()
/// ).await?
///
/// // List users by name in descending order (Z to A)
/// let paginated_users_desc = users.list_by_name(
///     PaginatedQueryArgs { first: 5, after: None },
///     ListDirection::Descending,
/// ).await?
/// ```
#[derive(Default, std::fmt::Debug, Clone, Copy)]
pub enum ListDirection {
    /// Sets the default direction variant to `Ascending`
    #[default]
    Ascending,
    Descending,
}

/// Structure to sort entities on a specific field when listing from database
///
/// Sort enum is used to specify the sorting order and the field to sort the entities by when listing them using `list_for_filters`
/// generated by [`EsRepo`][crate::EsRepo]. It is generated automatically for all fields which have `list_by` option. It encapsulates two fields,
/// first is `by` to specify the field name, second is `direction` which takes [`ListDirection`]
///
/// # Example
///
/// ```ignore
/// let result = users.list_for_filters(
///     UserFilters {
///         name: Some("Murphy".to_string()),
///     },
///     Sort {
///         // `UserSortBy::Id` and `UserSortBy::CreatedAt` are created by default,
///         // other columns need `list_by` to sort by
///         by: UserSortBy::Id,
///         direction: ListDirection::Descending,
///     },
///     PaginatedQueryArgs {
///         first: 10,
///         after: Default::default(),
///     },
/// )
/// .await?;
/// ```
#[derive(std::fmt::Debug, Clone, Copy)]
pub struct Sort<T> {
    // T parameter represents the field
    pub by: T,
    pub direction: ListDirection,
}

/// A cursor-based pagination structure for efficiently paginating through large datasets
///
/// The `PaginatedQueryArgs<T>` encapsulates a `first` field that specifies the count of entities to fetch per query, and an optional `after` field
/// that specifies the cursor to start from for the current query. The `<T>` parameter represents cursor type, which depends on the sorting field.
/// A field's cursor is generated by [`EsRepo`][crate::EsRepo] if it has `list_by` option.
///
/// # Examples
///
/// ```ignore
/// // Initial query - fetch first 10 users after an existing user id
/// let query_args = PaginatedQueryArgs {
///     first: 10,
///     after: Some(user_cursor::UserByIdCursor {
///         id: some_existing_user_id // assume this variable exists
///     }),
/// };
///
/// // Execute query using `query_args` argument of `PaginatedQueryArgs` type
/// let result = users.list_by_id(query_args, ListDirection::Ascending).await?;
///
/// // Continue pagination using the updated `next_query_args` of `PaginatedQueryArgs` type
/// if result.has_next_page {
///     let next_query_args = PaginatedQueryArgs {
///         first: 10,
///         after: result.end_cursor, // Use cursor from previous result to update `after`
///     };
///     let next_result = users.list_by_id(next_query_args, ListDirection::Ascending).await?;
/// }
/// ```
#[derive(Debug)]
pub struct PaginatedQueryArgs<T: std::fmt::Debug> {
    /// Specifies the number of entities to fetch per query
    pub first: usize,
    /// Specifies the cursor/marker to start from for current query
    pub after: Option<T>,
}

impl<T: std::fmt::Debug> Clone for PaginatedQueryArgs<T>
where
    T: Clone,
{
    fn clone(&self) -> Self {
        Self {
            first: self.first,
            after: self.after.clone(),
        }
    }
}

impl<T: std::fmt::Debug> Default for PaginatedQueryArgs<T> {
    /// Default value fetches first 100 entities
    fn default() -> Self {
        Self {
            first: 100,
            after: None,
        }
    }
}

/// Return type for paginated queries containing entities and pagination metadata
///
/// `PaginatedQueryRet` contains the fetched entities and utilities for continuing pagination.
/// Returned by the [`EsRepo`][crate::EsRepo] functions like `list_by`, `list_for` and `list_for_filters`.
/// Used with [`PaginatedQueryArgs`] to perform consistent and efficient pagination
///
/// The requested [`Self::requested_size`] and [`Self::end_cursor`] remain available
/// when callers move or filter [`Self::entities`]. [`Self::into_next_query`]
/// uses that metadata to continue with the existing [`PaginatedQueryArgs`] type.
///
/// # Examples
///
/// ```ignore
/// let query_args = PaginatedQueryArgs {
///     first: 10,
///     after: None,
/// };
///
/// // Execute query and get the `result` of type `PaginatedQueryRet`
/// let result = users.list_by_id(query_args, ListDirection::Ascending).await?;
///
/// // Continue pagination using the `next_query_args` argument updated using result
/// // Will continue only if 'has_next_page` returned from `result` is true
/// if result.has_next_page {
///     let next_query_args = PaginatedQueryArgs {
///         first: 10,
///         after: result.end_cursor, // update with 'end_cursor' of previous result
///     };
///     let next_result = users.list_by_id(next_query_args, ListDirection::Ascending).await?;
/// }
///
/// // Or use PaginatedQueryRet::into_next_query() convenience method
/// if let Some(next_query_args) = result.into_next_query() {
///     let next_result = users.list_by_id(next_query_args, ListDirection::Ascending).await?;
/// }
/// ```
/// Construction is gated behind [`Self::new`] and the entities vec is private.
/// The only way to move entities out is [`Self::drain`], which consumes the page
/// and returns a [`Continuation`] with no entity access, so reading a drained
/// page fails to compile instead of returning an empty list.
///
/// ```compile_fail
/// use es_entity::PaginatedQueryRet;
/// let page = PaginatedQueryRet::<u32, u32>::new(vec![1, 2, 3], false, None, 3);
/// let (_, continuation) = page.drain();
/// // The continuation no longer exposes the entities, so this does not compile.
/// let _ = continuation.entities();
/// ```
pub struct PaginatedQueryRet<T, C> {
    /// The number of entities requested for the page, copied from [`PaginatedQueryArgs::first`].
    requested_size: usize,
    /// [Vec] for the fetched `entities` by the paginated query
    entities: Vec<T>,
    /// [bool] for indicating if the list has been exhausted or more entities can be fetched
    pub has_next_page: bool,
    /// cursor on the last entity fetched to continue paginated queries.
    pub end_cursor: Option<C>,
}

impl<T, C> PaginatedQueryRet<T, C> {
    /// Creates a page result, recording how many entities were requested.
    ///
    /// Pass the same `first` that produced this page. It is stored independently of
    /// [`Self::entities`], so consuming or filtering the entities does not change it.
    pub fn new(
        entities: Vec<T>,
        has_next_page: bool,
        end_cursor: Option<C>,
        requested_size: usize,
    ) -> Self {
        Self {
            requested_size,
            entities,
            has_next_page,
            end_cursor,
        }
    }

    /// The number of entities that were requested for this page.
    pub fn requested_size(&self) -> usize {
        self.requested_size
    }

    /// Borrows the fetched entities without draining them.
    pub fn entities(&self) -> &[T] {
        &self.entities
    }

    /// Moves the entities out of the page, returning them alongside a
    /// [`Continuation`] that describes how to keep paginating.
    ///
    /// Draining consumes the page: the returned [`Continuation`] has no access to
    /// the entities, so reading a drained page fails to compile instead of
    /// returning an empty list.
    pub fn drain(self) -> (Vec<T>, Continuation<C>) {
        (
            self.entities,
            Continuation {
                requested_size: self.requested_size,
                has_next_page: self.has_next_page,
                end_cursor: self.end_cursor,
            },
        )
    }

    /// Converts the cursor type while preserving the requested size.
    pub fn map_end_cursor<C2>(self, f: impl FnOnce(C) -> C2) -> PaginatedQueryRet<T, C2> {
        PaginatedQueryRet {
            requested_size: self.requested_size,
            entities: self.entities,
            has_next_page: self.has_next_page,
            end_cursor: self.end_cursor.map(f),
        }
    }
}

/// The continuation of a page whose entities have already been drained.
///
/// It carries no entity access: only the metadata needed to fetch the next page.
pub struct Continuation<C> {
    requested_size: usize,
    has_next_page: bool,
    end_cursor: Option<C>,
}

impl<C> Continuation<C> {
    /// The number of entities that were requested for the drained page.
    pub fn requested_size(&self) -> usize {
        self.requested_size
    }

    /// Whether the drained page reported more results to fetch.
    pub fn has_next_page(&self) -> bool {
        self.has_next_page
    }

    /// The cursor on the last entity of the drained page.
    pub fn end_cursor(&self) -> Option<&C> {
        self.end_cursor.as_ref()
    }

    /// Creates the next query using the requested size and end cursor.
    ///
    /// Returns `None` after the last page or when the requested size was zero.
    pub fn into_next_query(self) -> Option<PaginatedQueryArgs<C>>
    where
        C: std::fmt::Debug,
    {
        if self.has_next_page && self.requested_size > 0 {
            Some(PaginatedQueryArgs {
                first: self.requested_size,
                after: self.end_cursor,
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn next_query_preserves_page_size_after_entities_are_moved() {
        for page_size in [1, 3, 100] {
            let page = PaginatedQueryRet::new(
                (0..page_size).collect(),
                true,
                Some(page_size - 1),
                page_size,
            );
            let (collected, continuation) = page.drain();

            let next = continuation.into_next_query().expect("another page exists");
            assert_eq!(next.first, page_size);
            assert_eq!(next.after, Some(page_size - 1));
            assert_eq!(collected.len(), page_size);
        }
    }

    #[test]
    fn next_query_size_is_independent_of_remaining_entities() {
        for count in [0, 1, 3, 7, 14] {
            let page =
                PaginatedQueryRet::new(vec![(); count], true, Some("last-fetched-entity"), 7);

            let next = page
                .drain()
                .1
                .into_next_query()
                .expect("another page exists");
            assert_eq!(next.first, 7);
            assert_eq!(next.after, Some("last-fetched-entity"));
        }
    }

    #[test]
    fn last_page_has_no_next_query() {
        for count in [0, 1, 7] {
            let page = PaginatedQueryRet::new(vec![(); count], false, count.checked_sub(1), 7);

            assert!(page.drain().1.into_next_query().is_none());
        }
    }

    #[test]
    fn zero_page_size_does_not_continue_even_when_more_entities_exist() {
        let page = PaginatedQueryRet::<(), usize>::new(Vec::new(), true, None, 0);

        assert!(page.drain().1.into_next_query().is_none());
    }

    #[test]
    fn drain_consumes_entities_and_keeps_the_requested_size() {
        let page = PaginatedQueryRet::new(vec![(); 7], true, Some(6), 10);
        assert_eq!(page.requested_size(), 10);

        let (entities, continuation) = page.drain();
        assert_eq!(entities.len(), 7);
        assert_eq!(continuation.requested_size(), 10);
        assert!(continuation.has_next_page());
        assert_eq!(continuation.end_cursor(), Some(&6));
    }
}
