//! Query execution infrastructure for event-sourced entities.
//!
//! This module provides the underlying query types used by the `es_query!` macro.
//! **These types are not intended to be used directly** - instead, use the `es_query!`
//! macro which provides a simpler interface for querying index tables and automatically
//! hydrating entities from their events.
//!
//! # Example
//!
//! Instead of using these types directly, use the `es_query!` macro:
//!
//! ```rust,ignore
//! es_query!(
//!     "SELECT id FROM users WHERE name = $1",
//!     name
//! ).fetch_optional(&pool).await
//! ```
//!
//! See the `es_query!` macro documentation for more details.

use crate::{
    db,
    error::{EntityHydrationError, StaleAggregateRead},
    events::{EntityEvents, EsQueryRow},
    one_time_executor::IntoOneTimeExecutor,
    operation::AtomicOperation,
    traits::*,
};

/// Shorthand for the entity-id type behind a repo.
type RepoId<Repo> = <<<Repo as EsRepo>::Entity as EsEntity>::Event as EsEvent>::EntityId;

/// Aggregate versions captured alongside a read, as `(root id, version)` pairs.
type VersionChecks<Repo> = Vec<(RepoId<Repo>, i32)>;

/// Raw rows split into the versions to validate and the event stream to hydrate.
type SplitRows<Repo> = (
    VersionChecks<Repo>,
    Vec<crate::events::GenericEvent<RepoId<Repo>>>,
);

/// A hydrated page plus its `has_more` flag.
type Page<Repo> = (Vec<<Repo as EsRepo>::Entity>, bool);

/// A hydrated page carrying the aggregate versions read with it.
type PageWithVersions<Repo> = (Vec<<Repo as EsRepo>::Entity>, bool, VersionChecks<Repo>);

/// A hydrated page carrying the ids of roots that moved during hydration.
type PageWithStale<Repo> = (Vec<<Repo as EsRepo>::Entity>, bool, Vec<RepoId<Repo>>);

/// Query builder for event-sourced entities.
///
/// This type is generated by the `es_query!` macro and should not be constructed directly.
/// It wraps a SQLx query and provides methods to fetch and hydrate entities from their events.
pub struct EsQuery<'q, Repo, Flavor, F, A> {
    inner: sqlx::query::Map<'q, db::Db, F, A>,
    _repo: std::marker::PhantomData<Repo>,
    _flavor: std::marker::PhantomData<Flavor>,
}

/// Query flavor for flat entities without nested relationships.
pub struct EsQueryFlavorFlat;

/// Query flavor for entities with nested relationships that need to be loaded recursively.
pub struct EsQueryFlavorNested;

// `R` is the row type the mapper yields. It is bound purely through `F`'s
// `Fn` output (an associated-type equality), so it needs no slot in `EsQuery`'s
// public generic list — adding one there would break every consumer that names
// the type.
impl<'q, Repo, Flavor, F, A, R> EsQuery<'q, Repo, Flavor, F, A>
where
    Repo: EsRepo,
    RepoId<Repo>: Unpin,
    R: EsQueryRow<Id = RepoId<Repo>> + Send + Unpin,
    F: FnMut(db::Row) -> Result<R, sqlx::Error> + Send,
    A: 'q + Send + sqlx::IntoArguments<'q, db::Db>,
{
    pub fn new(query: sqlx::query::Map<'q, db::Db, F, A>) -> Self {
        Self {
            inner: query,
            _repo: std::marker::PhantomData,
            _flavor: std::marker::PhantomData,
        }
    }

    /// Splits raw rows into the per-entity aggregate versions and the plain
    /// `GenericEvent` stream hydration expects.
    ///
    /// Every row of a given entity carries the same version (it comes from that
    /// entity's single index row), so the first row per id decides.
    fn split_versions(rows: Vec<R>) -> SplitRows<Repo>
    where
        RepoId<Repo>: Clone + PartialEq,
    {
        let mut versions: VersionChecks<Repo> = Vec::new();
        let generics = rows
            .into_iter()
            .map(|row| {
                if let Some(v) = row.aggregate_version() {
                    let generic = row.into_generic();
                    if versions.last().map(|(id, _)| id) != Some(&generic.entity_id) {
                        versions.push((generic.entity_id.clone(), v));
                    }
                    generic
                } else {
                    row.into_generic()
                }
            })
            .collect();
        (versions, generics)
    }

    async fn fetch_optional_inner<E: From<sqlx::Error> + From<EntityHydrationError>>(
        self,
        op: impl IntoOneTimeExecutor<'_>,
    ) -> Result<(Option<<Repo as EsRepo>::Entity>, VersionChecks<Repo>), E> {
        let executor = op.into_executor();
        let rows = executor.fetch_all(self.inner).await?;
        if rows.is_empty() {
            return Ok((None, Vec::new()));
        }

        let (versions, generics) = Self::split_versions(rows);
        Ok((EntityEvents::load_first(generics.into_iter())?, versions))
    }

    async fn fetch_n_inner<E: From<sqlx::Error> + From<EntityHydrationError>>(
        self,
        op: impl IntoOneTimeExecutor<'_>,
        first: usize,
    ) -> Result<PageWithVersions<Repo>, E> {
        let executor = op.into_executor();
        let rows = executor.fetch_all(self.inner).await?;
        let (versions, generics) = Self::split_versions(rows);
        let (entities, more) = EntityEvents::load_n(generics.into_iter(), first)?;
        Ok((entities, more, versions))
    }
}

// Flat repos are never aggregate roots (root implies nested children), so no
// versions are ever captured here — the plumbing below just discards the empty
// version vector.
impl<'q, Repo, F, A, R> EsQuery<'q, Repo, EsQueryFlavorFlat, F, A>
where
    Repo: EsRepo,
    RepoId<Repo>: Unpin + Clone + PartialEq,
    R: EsQueryRow<Id = RepoId<Repo>> + Send + Unpin,
    F: FnMut(db::Row) -> Result<R, sqlx::Error> + Send,
    A: 'q + Send + sqlx::IntoArguments<'q, db::Db>,
{
    /// Fetches at most one entity from the query results.
    ///
    /// Returns `Ok(None)` if no entities match the query, or `Ok(Some(entity))` if found.
    pub async fn fetch_optional(
        self,
        op: impl IntoOneTimeExecutor<'_>,
    ) -> Result<Option<<Repo as EsRepo>::Entity>, <Repo as EsRepo>::QueryError> {
        let (entity, _) = self
            .fetch_optional_inner::<<Repo as EsRepo>::QueryError>(op)
            .await?;
        Ok(entity)
    }

    /// Fetches up to `first` entities from the query results.
    ///
    /// Returns a tuple of (entities, has_more) where `has_more` indicates if there
    /// were more entities available beyond the requested limit.
    pub async fn fetch_n(
        self,
        op: impl IntoOneTimeExecutor<'_>,
        first: usize,
    ) -> Result<Page<Repo>, <Repo as EsRepo>::QueryError> {
        let (entities, more, _) = self
            .fetch_n_inner::<<Repo as EsRepo>::QueryError>(op, first)
            .await?;
        Ok((entities, more))
    }
}

impl<'q, Repo, F, A, R> EsQuery<'q, Repo, EsQueryFlavorNested, F, A>
where
    Repo: EsRepo,
    RepoId<Repo>: Unpin + Clone + PartialEq,
    R: EsQueryRow<Id = RepoId<Repo>> + Send + Unpin,
    F: FnMut(db::Row) -> Result<R, sqlx::Error> + Send,
    A: 'q + Send + sqlx::IntoArguments<'q, db::Db>,
    <Repo as EsRepo>::QueryError: From<StaleAggregateRead>,
{
    /// Stamps each hydrated entity with the version its parent row was read at,
    /// so a later update can CAS against it without an extra reload.
    fn apply_versions(entities: &mut [<Repo as EsRepo>::Entity], versions: &[(RepoId<Repo>, i32)]) {
        for entity in entities.iter_mut() {
            let id = entity.events().entity_id.clone();
            if let Some((_, v)) = versions.iter().find(|(vid, _)| *vid == id) {
                entity.events_mut().set_aggregate_version(*v);
            }
        }
    }
    /// Fetches at most one entity and loads all nested relationships.
    ///
    /// Returns `Ok(None)` if no entities match, or `Ok(Some(entity))` with all
    /// nested entities loaded if found.
    pub async fn fetch_optional<OP>(
        self,
        op: &mut OP,
    ) -> Result<Option<<Repo as EsRepo>::Entity>, <Repo as EsRepo>::QueryError>
    where
        OP: AtomicOperation,
    {
        let (entity, versions) = self
            .fetch_optional_inner::<<Repo as EsRepo>::QueryError>(&mut *op)
            .await?;
        let Some(entity) = entity else {
            return Ok(None);
        };
        let mut entities = [entity];
        <Repo as EsRepo>::load_all_nested_in_op::<_, <Repo as EsRepo>::QueryError>(
            op,
            &mut entities,
        )
        .await?;
        // Closing the bracket: the version was captured in the same statement
        // as the parent, so an unchanged version here proves no aggregate write
        // committed while the children were loading.
        if !versions.is_empty() {
            let stale = <Repo as EsRepo>::validate_aggregate_versions(op, &versions).await?;
            if !stale.is_empty() {
                return Err(StaleAggregateRead.into());
            }
        }
        Self::apply_versions(&mut entities, &versions);
        let [entity] = entities;
        Ok(Some(entity))
    }

    /// Fetches up to `first` entities and loads all nested relationships.
    ///
    /// Returns a tuple of (entities, has_more) where all entities have their nested
    /// relationships loaded, and `has_more` indicates if more entities were available.
    pub async fn fetch_n<OP>(
        self,
        op: &mut OP,
        first: usize,
    ) -> Result<Page<Repo>, <Repo as EsRepo>::QueryError>
    where
        OP: AtomicOperation,
    {
        let (entities, more, stale) = self.fetch_n_with_stale(op, first).await?;
        // User-written `es_query!` call sites do not auto-retry: the error
        // surfaces and the caller retries the op, the same contract as a
        // write-path `ConcurrentModification`. Generated batch fns instead call
        // `fetch_n_with_stale` and refetch just the stale roots.
        if !stale.is_empty() {
            return Err(StaleAggregateRead.into());
        }
        Ok((entities, more))
    }

    /// Like [`fetch_n`](EsQuery::fetch_n) but hands back the ids of roots whose
    /// aggregate version moved during hydration instead of erroring.
    ///
    /// Generated batch fns use this to refetch only the affected roots. Retrying
    /// the *whole* page instead would livelock: for a page of N aggregates a
    /// clean pass has probability (1−p)^N and each retry re-exposes all N to a
    /// fresh validation window, so under the very write load the check exists to
    /// survive, reads would start failing at scale. Partial refetch converges
    /// because a root that validated stays valid, so the stale set shrinks
    /// monotonically.
    #[doc(hidden)]
    pub async fn fetch_n_with_stale<OP>(
        self,
        op: &mut OP,
        first: usize,
    ) -> Result<PageWithStale<Repo>, <Repo as EsRepo>::QueryError>
    where
        OP: AtomicOperation,
    {
        let (mut entities, more, versions) = self
            .fetch_n_inner::<<Repo as EsRepo>::QueryError>(&mut *op, first)
            .await?;
        <Repo as EsRepo>::load_all_nested_in_op::<_, <Repo as EsRepo>::QueryError>(
            op,
            &mut entities,
        )
        .await?;
        let stale = if versions.is_empty() {
            Vec::new()
        } else {
            <Repo as EsRepo>::validate_aggregate_versions(op, &versions).await?
        };
        Self::apply_versions(&mut entities, &versions);
        Ok((entities, more, stale))
    }

    /// Like [`fetch_optional`](EsQuery::fetch_optional) but transitively includes
    /// soft-deleted nested entities.
    pub async fn fetch_optional_include_deleted<OP>(
        self,
        op: &mut OP,
    ) -> Result<Option<<Repo as EsRepo>::Entity>, <Repo as EsRepo>::QueryError>
    where
        OP: AtomicOperation,
    {
        let (entity, versions) = self
            .fetch_optional_inner::<<Repo as EsRepo>::QueryError>(&mut *op)
            .await?;
        let Some(entity) = entity else {
            return Ok(None);
        };
        let mut entities = [entity];
        <Repo as EsRepo>::load_all_nested_in_op_include_deleted::<_, <Repo as EsRepo>::QueryError>(
            op,
            &mut entities,
        )
        .await?;
        if !versions.is_empty() {
            let stale = <Repo as EsRepo>::validate_aggregate_versions(op, &versions).await?;
            if !stale.is_empty() {
                return Err(StaleAggregateRead.into());
            }
        }
        Self::apply_versions(&mut entities, &versions);
        let [entity] = entities;
        Ok(Some(entity))
    }

    /// Like [`fetch_n`](EsQuery::fetch_n) but transitively includes soft-deleted
    /// nested entities.
    pub async fn fetch_n_include_deleted<OP>(
        self,
        op: &mut OP,
        first: usize,
    ) -> Result<Page<Repo>, <Repo as EsRepo>::QueryError>
    where
        OP: AtomicOperation,
    {
        let (entities, more, stale) = self.fetch_n_include_deleted_with_stale(op, first).await?;
        if !stale.is_empty() {
            return Err(StaleAggregateRead.into());
        }
        Ok((entities, more))
    }

    /// [`fetch_n_with_stale`](EsQuery::fetch_n_with_stale) including soft-deleted
    /// nested entities.
    #[doc(hidden)]
    pub async fn fetch_n_include_deleted_with_stale<OP>(
        self,
        op: &mut OP,
        first: usize,
    ) -> Result<PageWithStale<Repo>, <Repo as EsRepo>::QueryError>
    where
        OP: AtomicOperation,
    {
        let (mut entities, more, versions) = self
            .fetch_n_inner::<<Repo as EsRepo>::QueryError>(&mut *op, first)
            .await?;
        <Repo as EsRepo>::load_all_nested_in_op_include_deleted::<_, <Repo as EsRepo>::QueryError>(
            op,
            &mut entities,
        )
        .await?;
        let stale = if versions.is_empty() {
            Vec::new()
        } else {
            <Repo as EsRepo>::validate_aggregate_versions(op, &versions).await?
        };
        Self::apply_versions(&mut entities, &versions);
        Ok((entities, more, stale))
    }
}
